config/routes.rb
Rails.application.routes.draw do
  resources :photo_check_ins
  resources :check_ins
  resources :audits
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :photo_entries
  resources :services
  resources :origins
  resources :pacients
  resources :visitors
  resources :users
  match '/search_order' => 'entries#search_order', :via => [:get, :post, :put]
  
  get 'home/index'
  get 'vistors/index'
  root to: 'entries#new'
  # root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entries do
    member do 
      post 'check_in'
      get 'get_photos'
      get 'get_audits'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/audit.rb
class Audit < ApplicationRecord
	belongs_to :user, :optional => true
	belongs_to :entry, :optional => true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
	belongs_to :entry, class_name: "Entry", foreign_key: "entry_id"
	belongs_to :check_in_by, class_name: "User", foreign_key: "check_in_by_id",:optional => true

	has_many :photo_check_ins
  accepts_nested_attributes_for :photo_check_ins
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :pacient, class_name: "Pacient", foreign_key: "pacient_id"
	accepts_nested_attributes_for :pacient
	belongs_to :origin, class_name: "Origin", foreign_key: "origin_id"
	accepts_nested_attributes_for :origin
	belongs_to :service, class_name: "Service", foreign_key: "service_id"
	accepts_nested_attributes_for :service
	
	belongs_to :created_by, class_name: "User", foreign_key: "created_by_id", :optional => true
	belongs_to :check_in_by, class_name: "User", foreign_key: "check_in_by_id",:optional => true

	has_many :photo_entries
  accepts_nested_attributes_for :photo_entries

  has_many :check_ins
  accepts_nested_attributes_for :check_ins

  has_many :audits

  validates :order_id, presence: true, uniqueness: true

  # after_save :save_activity

  attr_accessor :current_user, :ip_address

  def save_activity(action)
  	# Ingreso creado
  	# Ingreso verificado
  	# Ingreso visualizado

  	audit = Audit.new
  	audit.user_id = self.current_user.id if self.current_user
  	audit.entry_id = self.id
  	audit.ip = self.ip_address
  	audit.action = action
  	audit.date = Time.now
  	audit.save
  end
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/pacient.rb
class Pacient < ApplicationRecord
	def full_name
		"#{self.name_1} #{self.name_2} #{self.last_name_1} #{self.last_name_2}"
	end

	def age
    # self.birthday.present? ? Time.now.year - self.birthday.year : 0
   	#  dob = self.birthday
   	#  now = Time.zone.now
  	# now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  	self.birthday.present? ? ((Time.zone.now - self.birthday.to_time) / 1.year.seconds).floor : 0
  end
end

app/models/photo_check_in.rb
class PhotoCheckIn < ApplicationRecord
	belongs_to :entry, class_name: "Entry", foreign_key: "entry_id"
	belongs_to :check_id, class_name: "CheckIn", foreign_key: "check_in_id"
	mount_base64_uploader :photo, PhotoUploader
end

app/models/photo_entry.rb
class PhotoEntry < ApplicationRecord
	belongs_to :entry, class_name: "Entry", foreign_key: "entry_id"
	mount_base64_uploader :photo, PhotoUploader
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
	def role_name
    if self.name == "admin"
      "Administrador del Sistema"
    elsif self.name == "supervisor"
      "Supervisor"
    elsif self.name == "receptionist"
      "Recepcionista"
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable, authentication_keys: [:login]

  validates :login, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  attr_writer :login_user
  
  def login_user
    @login_user || self.login || self.email
  end

  def email_required?
	  false
	end

	def role_name
    if self.roles.first.present?
      if self.roles.first.name == "admin"
        "Administrador del Sistema"
      elsif self.roles.first.name == "supervisor"
        "Supervisor"
      elsif self.roles.first.name == "receptionist"
        "Recepcionista"
      end
    else
      "Sin Asignar"
    end
  end

end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :ci, :company_id, :email, :direction, :gender_id, :birthday, :photo, :signature)
    end
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/vistors_helper.rb
module VistorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ci %>
    <%= form.text_field :ci %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= form.text_field :direction %>
  </div>

  <div class="field">
    <%= form.label :gender_id %>
    <%= form.number_field :gender_id %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.datetime_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :signature %>
    <%= form.text_field :signature %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ci</th>
      <th>Company</th>
      <th>Email</th>
      <th>Direction</th>
      <th>Gender</th>
      <th>Birthday</th>
      <th>Photo</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.name %></td>
        <td><%= visitor.ci %></td>
        <td><%= visitor.company_id %></td>
        <td><%= visitor.email %></td>
        <td><%= visitor.direction %></td>
        <td><%= visitor.gender_id %></td>
        <td><%= visitor.birthday %></td>
        <td><%= visitor.photo %></td>
        <td><%= visitor.signature %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @visitor.ci %>
</p>

<p>
  <strong>Company:</strong>
  <%= @visitor.company_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @visitor.direction %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @visitor.gender_id %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @visitor.birthday %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @visitor.photo %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @visitor.signature %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>