config/routes.rb
Rails.application.routes.draw do
  resources :photo_check_ins
  resources :check_ins
  resources :audits
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :photo_entries
  resources :services
  resources :origins
  resources :pacients
  resources :visitors
  resources :users
  match '/search_order' => 'entries#search_order', :via => [:get, :post, :put]
  
  get 'home/index'
  get 'vistors/index'
  root to: 'entries#new'
  # root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entries do
    member do 
      post 'check_in'
      get 'get_photos'
      get 'get_audits'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable, authentication_keys: [:login]

  validates :login, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  attr_writer :login_user
  
  def login_user
    @login_user || self.login || self.email
  end

  def email_required?
	  false
	end

	def role_name
    if self.roles.first.present?
      if self.roles.first.name == "admin"
        "Administrador del Sistema"
      elsif self.roles.first.name == "supervisor"
        "Supervisor"
      elsif self.roles.first.name == "receptionist"
        "Recepcionista"
      end
    else
      "Sin Asignar"
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :get_stations
  layout "blank"
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    user = User.where(:login => params[:user][:login]).last
    if user.present? && user.has_role?(:receptionist)
      user.station_name = params[:user][:station_name]
      user.save
    end
    super
  end

  # DELETE /resource/sign_out
  def destroy
    user = current_user
    user.station_name = nil
    user.save
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :get_roles, only: [:new, :create, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    Rails.logger.info "=====>>>>>@user.valid?: #{@user.valid?}"
    Rails.logger.info "=====>>>>>@user.errors: #{@user.errors.full_messages}"
    respond_to do |format|
      if @user.save

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # params.fetch(:user, {})
      params.require(:user).permit(:id, :email, :name, :login, :active, :photo, :signature, :encrypted_password, :password, :role_ids)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for(@user) do |f| %>
      <div class="row">
	      <div class="col-md-6">
	        <%= f.input :login %>
	      </div>
	      <div class="col-md-6">
	      	<div style="padding-bottom: 10px;position: relative;">
	      		<%= f.label user.new_record? ? "Nueva contraseña" : "Editar contraseña?" %>
		        <span class="change_password"><%= check_box_tag("change_password") %></span>
		        <% if user.new_record? %> 
			        <%= f.password_field :password, autocomplete: "off", :class => "form-control" %>
			      <% else %> 
			        <%= f.password_field :password, autocomplete: "off", :class => "form-control", :disabled => true %>
			      <% end %> 	
	      	</div>
	      </div>
	      <div class="col-md-12">
	        <%= f.input :name %>    
	      </div>
	      <div class="col-md-12">
	        <%= f.input :email %>
	      </div>

	      
		      <div class="col-md-12">
		        <%= f.input :role_ids, collection: @all_roles, label_method: lambda { |p| "#{p.role_name}"}, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
		      </div>
		    
				<div class="col-md-12">
	        <%= f.input :active %>
	      </div>

	      <input type="hidden" name="url" id="url" value="">

	    </div>	   
      <div class="row">
        <div class="col-md-12">
        	<div class="actions">
	          <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
	      		<%= f.submit "Guardar", class: 'btn btn-success' %>
	      	</div>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Zoom Next - Usuarios</h1>
  </div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Datos del Usuario</h6>
    </div>
    <div class="card-body">
    	<%= render 'form', user: @user %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Zoom Next Visualización de Usuarios</h1>
    <a href="<%= new_user_path %>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Nuevo usuario</a>

  </div>
  <!-- Page Heading -->

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Información del Ingreso</h6>
    </div>
    <div class="card-body">
      

      <div class="row">
        <div class="col-md-12">
          <div class="table-responsive">
            <table class="table table-bordered responsive" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Usuario</th>
                  <th>Nombre completo</th>
                  <th>Correo electrónico</th>
                  <th>Estación</th>
                  <th>Creado en</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>Usuario</th>
                  <th>Nombre completo</th>
                  <th>Correo electrónico</th>
                  <th>Estación</th>
                  <th>Creado en</th>
                </tr>
              </tfoot>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= link_to user.login, user %></td>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.station_name.present? ? user.station_name : "No conectado" %></td>
                    <td><%= l(user.created_at, format: @date_time_format_words) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  lng = {
    "sProcessing":     "Procesando...",
    "sLengthMenu":     "Mostrar _MENU_ registros",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
      "sFirst":    "Primero",
      "sLast":     "Último",
      "sNext":     "Siguiente",
      "sPrevious": "Anterior"
    },
    "oAria": {
      "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
      "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
  }
  $('#dataTable').DataTable({
    searching: false,
    "order": [[ 1, "desc" ]],
    "columnDefs": [
        {
          "targets": [ 1 ],
          "visible": false
        },
    ],
    "language": lng
  });
</script>

app/views/users/new.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Zoom Next - Usuarios</h1>
  </div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Datos del Usuario</h6>
    </div>
    <div class="card-body">
    	<%= render 'form', user: @user %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Zoom Next - Usuarios</h1>
  </div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Datos del Usuario</h6>
    </div>
    <div class="card-body">
    	<p>
    		<label>Usuario:</label>
    		<%= @user.login%>
    	</p>
    	<p>
    		<label>Nombre:</label>
    		<%= @user.name %>
    	</p>
    	<p>
    		<label>Correo Electrónico:</label>
    		<%= @user.email %>
    	</p>
    	<p>
    		<label>Estación:</label>
    		<%= @user.station_name.present? ? @user.station_name : "No conectado" %>
    	</p>
    	<p>
    		<label>Creado en:</label>
    		<%= l(@user.created_at, format: @date_time_format_words) %>
    	</p>
    	<%= link_to 'Editar', edit_user_path(@user) %>
    </div>
    
  </div>
</div>